-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "rocketjaket"."inventory_product" add column "min_available_qty" integer
--  null;
