version: "3.8"
services:
  custom-api:
    build:
      context: ./custom-api
      target: dev
    volumes:
      - ./custom-api:/src
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*

  whatsapp-node-api:
    build:
      context: ./whatsapp-node-api
    command: npm start
    restart: always
    volumes:
      - ./whatsapp-node-api:/app
    ports:
      - "5000:5000"
