-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "rocketjaket"."transaction" add column "cash_in_amount" integer
--  not null;
