-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "rocketjaket"."transaction_item" add column "capital_price" integer
--  not null;
